#!/usr/bin/env node
/**
 * KinderSpark Pro — Translation Sync Script
 *
 * Reads translations/master.json and generates:
 *   - frontend/lib/i18n.ts        (Web / Next.js)
 *   - translations/ios/            (iOS .strings files per language)
 *   - translations/android/        (Android strings.xml per language)
 *
 * Usage:
 *   node translations/sync.js
 *   node translations/sync.js --check   (check for missing keys, no write)
 *   node translations/sync.js --lang fr (only output one language)
 */

const fs   = require('fs');
const path = require('path');

const ROOT   = path.join(__dirname, '..');
const MASTER = path.join(__dirname, 'master.json');

const master = JSON.parse(fs.readFileSync(MASTER, 'utf8'));
const { languages, rtlLanguages } = master._meta;
const keys = master.keys;

const args       = process.argv.slice(2);
const checkOnly  = args.includes('--check');
const onlyLang   = args.includes('--lang') ? args[args.indexOf('--lang') + 1] : null;
const targetLangs = onlyLang ? [onlyLang] : languages;

let missingCount = 0;

// ── 1. Check for missing translations ───────────────────────────────────────
console.log('\n🔍 Checking for missing translations...');
for (const key of Object.keys(keys)) {
  for (const lang of languages) {
    if (!keys[key][lang]) {
      console.warn(`  ⚠️  MISSING: [${lang}] ${key}`);
      missingCount++;
    }
  }
}
if (missingCount === 0) {
  console.log('  ✅ All translations present');
} else {
  console.log(`  ⚠️  ${missingCount} missing translations (Claude agent will fill these)`);
}
if (checkOnly) process.exit(missingCount > 0 ? 1 : 0);

// ── 2. Generate Web: frontend/lib/i18n.ts ───────────────────────────────────
console.log('\n🌐 Generating frontend/lib/i18n.ts...');

const localeType = `export type Locale = ${languages.map(l => `'${l}'`).join(' | ')};`;

const localesArray = languages.map(lang => {
  const isRTL = rtlLanguages.includes(lang);
  const names = { en:'English', fr:'Français', es:'Español', ar:'العربية', ur:'اردو', hi:'हिन्दी', zh:'中文', pt:'Português', de:'Deutsch', tr:'Türkçe' };
  const flags = { en:'🇬🇧', fr:'🇫🇷', es:'🇪🇸', ar:'🇸🇦', ur:'🇵🇰', hi:'🇮🇳', zh:'🇨🇳', pt:'🇧🇷', de:'🇩🇪', tr:'🇹🇷' };
  return `  { code: '${lang}', name: '${names[lang] || lang}', dir: '${isRTL ? 'rtl' : 'ltr'}', flag: '${flags[lang] || '🌐'}' }`;
});

const translationsObj = languages.map(lang => {
  const entries = Object.keys(keys)
    .filter(k => keys[k][lang])
    .map(k => `    '${k}': ${JSON.stringify(keys[k][lang])}`)
    .join(',\n');
  return `  ${lang}: {\n${entries}\n  }`;
});

const i18nContent = `// AUTO-GENERATED by translations/sync.js — DO NOT EDIT DIRECTLY
// Edit translations/master.json then run: node translations/sync.js

${localeType}

export const LOCALES: { code: Locale; name: string; dir: 'ltr' | 'rtl'; flag: string }[] = [
${localesArray.join(',\n')}
];

export const translations: Record<Locale, Record<string, string>> = {
${translationsObj.join(',\n')}
};

export function t(key: string, locale: Locale = 'en'): string {
  return translations[locale]?.[key] ?? translations.en[key] ?? key;
}
`;

fs.writeFileSync(path.join(ROOT, 'frontend/lib/i18n.ts'), i18nContent);
console.log('  ✅ frontend/lib/i18n.ts written');

// ── 3. Generate iOS: .strings files ─────────────────────────────────────────
console.log('\n🍎 Generating iOS .strings files...');

for (const lang of targetLangs) {
  const iosLang = lang === 'zh' ? 'zh-Hans' : lang;
  const dir = path.join(__dirname, `ios/${iosLang}.lproj`);
  fs.mkdirSync(dir, { recursive: true });

  const lines = [
    `/* KinderSpark Pro — ${iosLang} */`,
    `/* AUTO-GENERATED by translations/sync.js — DO NOT EDIT */`,
    `/* Edit translations/master.json then run: node translations/sync.js */`,
    ''
  ];

  for (const key of Object.keys(keys)) {
    const val = keys[key][lang] || keys[key]['en'];
    const iosKey = key.replace(/\./g, '_');
    lines.push(`"${iosKey}" = ${JSON.stringify(val)};`);
  }

  fs.writeFileSync(path.join(dir, 'Localizable.strings'), lines.join('\n'));
  console.log(`  ✅ ios/${iosLang}.lproj/Localizable.strings`);
}

// ── 4. Generate Android: strings.xml files ──────────────────────────────────
console.log('\n🤖 Generating Android strings.xml files...');

for (const lang of targetLangs) {
  const androidLang = lang === 'en' ? 'values' : `values-${lang === 'zh' ? 'zh-rCN' : lang}`;
  const dir = path.join(__dirname, `android/${androidLang}`);
  fs.mkdirSync(dir, { recursive: true });

  const xmlLines = [
    '<?xml version="1.0" encoding="utf-8"?>',
    '<!-- AUTO-GENERATED by translations/sync.js — DO NOT EDIT -->',
    '<!-- Edit translations/master.json then run: node translations/sync.js -->',
    '<resources>'
  ];

  for (const key of Object.keys(keys)) {
    const val = (keys[key][lang] || keys[key]['en'])
      .replace(/&/g, '&amp;')
      .replace(/</g, '&lt;')
      .replace(/>/g, '&gt;')
      .replace(/'/g, "\\'");
    const androidKey = key.replace(/\./g, '_');
    xmlLines.push(`    <string name="${androidKey}">${val}</string>`);
  }

  xmlLines.push('</resources>');
  fs.writeFileSync(path.join(dir, 'strings.xml'), xmlLines.join('\n'));
  console.log(`  ✅ android/${androidLang}/strings.xml`);
}

// ── 5. Summary ───────────────────────────────────────────────────────────────
const keyCount  = Object.keys(keys).length;
const langCount = languages.length;
console.log(`\n✨ Sync complete!`);
console.log(`   ${keyCount} keys × ${langCount} languages = ${keyCount * langCount} translations`);
console.log(`   Platforms: Web (i18n.ts) + iOS (.strings) + Android (strings.xml)`);
if (missingCount > 0) {
  console.log(`   ⚠️  Run the i18n GitHub Action to auto-fill ${missingCount} missing translations`);
}
