export interface ModuleItem {
  w: string
  e: string
  hint?: string
}

export interface Module {
  id: string
  title: string
  icon: string
  color: string
  type: 'numbers' | 'letters' | 'words' | 'colors' | 'items'
  items: ModuleItem[]
}

export const MODS: Module[] = [
  {
    id: 'numbers',
    title: 'Numbers',
    icon: '🔢',
    color: '#5E5CE6',
    type: 'numbers',
    items: [
      { w: 'One', e: '1️⃣', hint: '1 apple' },
      { w: 'Two', e: '2️⃣', hint: '2 balloons' },
      { w: 'Three', e: '3️⃣', hint: '3 stars' },
      { w: 'Four', e: '4️⃣', hint: '4 wheels' },
      { w: 'Five', e: '5️⃣', hint: '5 fingers' },
      { w: 'Six', e: '6️⃣', hint: '6 eggs' },
      { w: 'Seven', e: '7️⃣', hint: '7 rainbow colors' },
      { w: 'Eight', e: '8️⃣', hint: '8 legs on spider' },
      { w: 'Nine', e: '9️⃣', hint: '9 planets' },
      { w: 'Ten', e: '🔟', hint: '10 toes' },
    ],
  },
  {
    id: 'letters',
    title: 'Letters',
    icon: '🔤',
    color: '#BF5AF2',
    type: 'letters',
    items: [
      { w: 'A', e: '🍎', hint: 'Apple starts with A' },
      { w: 'B', e: '🦋', hint: 'Butterfly starts with B' },
      { w: 'C', e: '🐱', hint: 'Cat starts with C' },
      { w: 'D', e: '🐶', hint: 'Dog starts with D' },
      { w: 'E', e: '🐘', hint: 'Elephant starts with E' },
      { w: 'F', e: '🐸', hint: 'Frog starts with F' },
      { w: 'G', e: '🦒', hint: 'Giraffe starts with G' },
      { w: 'H', e: '🐴', hint: 'Horse starts with H' },
      { w: 'I', e: '🍦', hint: 'Ice cream starts with I' },
      { w: 'J', e: '🃏', hint: 'Joker starts with J' },
      { w: 'K', e: '🦘', hint: 'Kangaroo starts with K' },
      { w: 'L', e: '🦁', hint: 'Lion starts with L' },
      { w: 'M', e: '🐵', hint: 'Monkey starts with M' },
      { w: 'N', e: '🦅', hint: 'No starts with N' },
      { w: 'O', e: '🦦', hint: 'Otter starts with O' },
      { w: 'P', e: '🐼', hint: 'Panda starts with P' },
      { w: 'Q', e: '👸', hint: 'Queen starts with Q' },
      { w: 'R', e: '🌈', hint: 'Rainbow starts with R' },
      { w: 'S', e: '⭐', hint: 'Star starts with S' },
      { w: 'T', e: '🐯', hint: 'Tiger starts with T' },
      { w: 'U', e: '☂️', hint: 'Umbrella starts with U' },
      { w: 'V', e: '🎻', hint: 'Violin starts with V' },
      { w: 'W', e: '🐳', hint: 'Whale starts with W' },
      { w: 'X', e: '🎵', hint: 'Xylophone starts with X' },
      { w: 'Y', e: '🧶', hint: 'Yarn starts with Y' },
      { w: 'Z', e: '🦓', hint: 'Zebra starts with Z' },
    ],
  },
  {
    id: 'words',
    title: 'Sight Words',
    icon: '📝',
    color: '#FF9F0A',
    type: 'words',
    items: [
      { w: 'the', e: '📖', hint: 'The dog runs' },
      { w: 'and', e: '🔗', hint: 'You and me' },
      { w: 'is', e: '✅', hint: 'This is fun' },
      { w: 'in', e: '📦', hint: 'In the box' },
      { w: 'it', e: '👆', hint: 'It is big' },
      { w: 'you', e: '👤', hint: 'I see you' },
      { w: 'that', e: '👉', hint: 'That is mine' },
      { w: 'he', e: '👦', hint: 'He can run' },
      { w: 'was', e: '⏮️', hint: 'It was nice' },
      { w: 'for', e: '🎁', hint: 'This is for you' },
    ],
  },
  {
    id: 'colors',
    title: 'Colors',
    icon: '🎨',
    color: '#FF453A',
    type: 'colors',
    items: [
      { w: 'Red', e: '🔴', hint: 'Like an apple' },
      { w: 'Blue', e: '🔵', hint: 'Like the sky' },
      { w: 'Green', e: '🟢', hint: 'Like grass' },
      { w: 'Yellow', e: '🟡', hint: 'Like the sun' },
      { w: 'Orange', e: '🟠', hint: 'Like an orange' },
      { w: 'Purple', e: '🟣', hint: 'Like grapes' },
      { w: 'Pink', e: '🌸', hint: 'Like flamingo' },
      { w: 'Brown', e: '🟤', hint: 'Like chocolate' },
      { w: 'Black', e: '⚫', hint: 'Like night' },
      { w: 'White', e: '⚪', hint: 'Like snow' },
    ],
  },
  {
    id: 'animals',
    title: 'Animals',
    icon: '🐾',
    color: '#30D158',
    type: 'items',
    items: [
      { w: 'Dog', e: '🐶', hint: 'Says woof' },
      { w: 'Cat', e: '🐱', hint: 'Says meow' },
      { w: 'Lion', e: '🦁', hint: 'King of jungle' },
      { w: 'Elephant', e: '🐘', hint: 'Has big ears' },
      { w: 'Giraffe', e: '🦒', hint: 'Very long neck' },
      { w: 'Monkey', e: '🐵', hint: 'Loves bananas' },
      { w: 'Tiger', e: '🐯', hint: 'Has stripes' },
      { w: 'Bear', e: '🐻', hint: 'Loves honey' },
      { w: 'Penguin', e: '🐧', hint: 'Lives in cold' },
      { w: 'Rabbit', e: '🐰', hint: 'Hops around' },
    ],
  },
  {
    id: 'fruits',
    title: 'Fruits',
    icon: '🍎',
    color: '#FF453A',
    type: 'items',
    items: [
      { w: 'Apple', e: '🍎', hint: 'Red and sweet' },
      { w: 'Banana', e: '🍌', hint: 'Yellow and curved' },
      { w: 'Mango', e: '🥭', hint: 'Tropical and sweet' },
      { w: 'Orange', e: '🍊', hint: 'Citrus fruit' },
      { w: 'Grape', e: '🍇', hint: 'Grows in bunch' },
      { w: 'Strawberry', e: '🍓', hint: 'Red with seeds' },
      { w: 'Pineapple', e: '🍍', hint: 'Has spiky top' },
      { w: 'Watermelon', e: '🍉', hint: 'Green outside red inside' },
      { w: 'Cherry', e: '🍒', hint: 'Comes in pairs' },
      { w: 'Lemon', e: '🍋', hint: 'Very sour' },
    ],
  },
  {
    id: 'shapes',
    title: 'Shapes',
    icon: '🔷',
    color: '#5E5CE6',
    type: 'items',
    items: [
      { w: 'Circle', e: '⭕', hint: 'Round like ball' },
      { w: 'Square', e: '🟥', hint: '4 equal sides' },
      { w: 'Triangle', e: '🔺', hint: '3 sides' },
      { w: 'Rectangle', e: '▬', hint: '2 long 2 short sides' },
      { w: 'Star', e: '⭐', hint: '5 points' },
      { w: 'Heart', e: '❤️', hint: 'Shape of love' },
      { w: 'Diamond', e: '💎', hint: 'Like a kite' },
      { w: 'Oval', e: '🥚', hint: 'Stretched circle' },
    ],
  },
  {
    id: 'food',
    title: 'Food',
    icon: '🍔',
    color: '#FF9F0A',
    type: 'items',
    items: [
      { w: 'Pizza', e: '🍕', hint: 'Round and cheesy' },
      { w: 'Bread', e: '🍞', hint: 'Made from wheat' },
      { w: 'Milk', e: '🥛', hint: 'From a cow' },
      { w: 'Egg', e: '🥚', hint: 'From a chicken' },
      { w: 'Rice', e: '🍚', hint: 'White small grains' },
      { w: 'Soup', e: '🍲', hint: 'Hot liquid food' },
      { w: 'Cake', e: '🎂', hint: 'Sweet birthday food' },
      { w: 'Cookie', e: '🍪', hint: 'Sweet baked snack' },
    ],
  },
  {
    id: 'vehicles',
    title: 'Vehicles',
    icon: '🚗',
    color: '#BF5AF2',
    type: 'items',
    items: [
      { w: 'Car', e: '🚗', hint: '4 wheels drive' },
      { w: 'Bus', e: '🚌', hint: 'Carries many people' },
      { w: 'Airplane', e: '✈️', hint: 'Flies in sky' },
      { w: 'Boat', e: '⛵', hint: 'Sails on water' },
      { w: 'Train', e: '🚂', hint: 'Runs on tracks' },
      { w: 'Bicycle', e: '🚲', hint: '2 wheels pedal' },
      { w: 'Truck', e: '🚚', hint: 'Carries heavy loads' },
      { w: 'Rocket', e: '🚀', hint: 'Goes to space' },
    ],
  },
  {
    id: 'weather',
    title: 'Weather',
    icon: '⛅',
    color: '#30D158',
    type: 'items',
    items: [
      { w: 'Sun', e: '☀️', hint: 'Bright and warm' },
      { w: 'Rain', e: '🌧️', hint: 'Water from clouds' },
      { w: 'Snow', e: '❄️', hint: 'White and cold' },
      { w: 'Wind', e: '💨', hint: 'Moving air' },
      { w: 'Cloud', e: '☁️', hint: 'Floats in sky' },
      { w: 'Storm', e: '⛈️', hint: 'Thunder and lightning' },
      { w: 'Rainbow', e: '🌈', hint: '7 colors after rain' },
      { w: 'Fog', e: '🌫️', hint: 'Hard to see through' },
    ],
  },
  {
    id: 'body',
    title: 'Body Parts',
    icon: '👁️',
    color: '#FF453A',
    type: 'items',
    items: [
      { w: 'Eyes', e: '👁️', hint: 'You see with' },
      { w: 'Ears', e: '👂', hint: 'You hear with' },
      { w: 'Nose', e: '👃', hint: 'You smell with' },
      { w: 'Mouth', e: '👄', hint: 'You eat and talk' },
      { w: 'Hands', e: '👐', hint: 'You clap and hold' },
      { w: 'Feet', e: '🦶', hint: 'You walk on' },
      { w: 'Head', e: '🗣️', hint: 'Top of your body' },
      { w: 'Heart', e: '❤️', hint: 'Pumps your blood' },
    ],
  },
  {
    id: 'family',
    title: 'Family',
    icon: '👨‍👩‍👧',
    color: '#FF9F0A',
    type: 'items',
    items: [
      { w: 'Mama', e: '👩', hint: 'Your mother' },
      { w: 'Baba', e: '👨', hint: 'Your father' },
      { w: 'Baby', e: '👶', hint: 'Youngest in family' },
      { w: 'Brother', e: '👦', hint: 'Boy sibling' },
      { w: 'Sister', e: '👧', hint: 'Girl sibling' },
      { w: 'Grandma', e: '👵', hint: 'Mother\'s mother' },
      { w: 'Grandpa', e: '👴', hint: 'Father\'s father' },
      { w: 'Family', e: '👨‍👩‍👧‍👦', hint: 'All together' },
    ],
  },
]

export const TUTOR_TOPICS = [
  { id: 'numbers', label: 'Numbers', emoji: '🔢', color: '#5E5CE6' },
  { id: 'letters', label: 'Letters', emoji: '🔤', color: '#BF5AF2' },
  { id: 'animals', label: 'Animals', emoji: '🐾', color: '#30D158' },
  { id: 'colors', label: 'Colors', emoji: '🎨', color: '#FF453A' },
  { id: 'shapes', label: 'Shapes', emoji: '🔷', color: '#FF9F0A' },
  { id: 'fruits', label: 'Fruits', emoji: '🍎', color: '#FF453A' },
]

export const QB: Record<string, any[]> = {
  numbers: [
    { q: 'How many fingers do you have?', a: '10', choices: ['8', '9', '10', '11'], e: '✋' },
    { q: 'What comes after 3?', a: '4', choices: ['2', '4', '5', '6'], e: '🔢' },
    { q: 'How many sides does a triangle have?', a: '3', choices: ['2', '3', '4', '5'], e: '🔺' },
    { q: 'Count the stars: ⭐⭐⭐⭐⭐', a: '5', choices: ['3', '4', '5', '6'], e: '⭐' },
    { q: 'What number is "seven"?', a: '7', choices: ['6', '7', '8', '9'], e: '7️⃣' },
    { q: 'What is 2 + 2?', a: '4', choices: ['3', '4', '5', '6'], e: '➕' },
    { q: 'What is 1 + 3?', a: '4', choices: ['3', '4', '5', '7'], e: '🧮' },
    { q: 'How many wheels does a car have?', a: '4', choices: ['2', '3', '4', '6'], e: '🚗' },
    { q: 'What comes before 10?', a: '9', choices: ['7', '8', '9', '11'], e: '🔟' },
    { q: 'How many legs does a dog have?', a: '4', choices: ['2', '4', '6', '8'], e: '🐶' },
    { q: 'What is 5 - 2?', a: '3', choices: ['2', '3', '4', '5'], e: '➖' },
    { q: 'How many eggs in half a dozen?', a: '6', choices: ['4', '5', '6', '8'], e: '🥚' },
  ],
  letters: [
    { q: 'What letter starts "Apple"?', a: 'A', choices: ['A', 'B', 'C', 'D'], e: '🍎' },
    { q: 'What letter starts "Ball"?', a: 'B', choices: ['A', 'B', 'D', 'P'], e: '⚽' },
    { q: 'What letter starts "Cat"?', a: 'C', choices: ['B', 'C', 'K', 'S'], e: '🐱' },
    { q: 'What letter starts "Dog"?', a: 'D', choices: ['B', 'D', 'G', 'P'], e: '🐶' },
    { q: 'What letter starts "Elephant"?', a: 'E', choices: ['A', 'E', 'I', 'O'], e: '🐘' },
    { q: 'What letter starts "Fish"?', a: 'F', choices: ['F', 'P', 'S', 'V'], e: '🐟' },
    { q: 'What letter starts "Giraffe"?', a: 'G', choices: ['C', 'G', 'J', 'Z'], e: '🦒' },
    { q: 'What letter starts "Hat"?', a: 'H', choices: ['A', 'H', 'M', 'N'], e: '🎩' },
    { q: 'What letter starts "Ice cream"?', a: 'I', choices: ['A', 'E', 'I', 'U'], e: '🍦' },
    { q: 'What letter starts "Juice"?', a: 'J', choices: ['G', 'J', 'Q', 'Y'], e: '🧃' },
    { q: 'What letter starts "Kite"?', a: 'K', choices: ['C', 'K', 'Q', 'X'], e: '🪁' },
    { q: 'What letter starts "Lion"?', a: 'L', choices: ['I', 'J', 'L', 'N'], e: '🦁' },
  ],
  animals: [
    { q: 'Which animal says "Meow"?', a: 'Cat', choices: ['Dog', 'Cat', 'Cow', 'Duck'], e: '🐱' },
    { q: 'Which animal has a long neck?', a: 'Giraffe', choices: ['Elephant', 'Giraffe', 'Lion', 'Zebra'], e: '🦒' },
    { q: 'Which animal lives in the ocean?', a: 'Whale', choices: ['Lion', 'Eagle', 'Whale', 'Tiger'], e: '🐳' },
    { q: 'Which animal has stripes?', a: 'Zebra', choices: ['Giraffe', 'Zebra', 'Lion', 'Bear'], e: '🦓' },
    { q: 'Which animal can fly?', a: 'Eagle', choices: ['Dog', 'Cat', 'Eagle', 'Fish'], e: '🦅' },
    { q: 'Which animal gives us milk?', a: 'Cow', choices: ['Pig', 'Cow', 'Horse', 'Sheep'], e: '🐄' },
    { q: 'Which animal has a trunk?', a: 'Elephant', choices: ['Rhino', 'Hippo', 'Elephant', 'Bear'], e: '🐘' },
    { q: 'Which is the biggest animal?', a: 'Blue Whale', choices: ['Elephant', 'Giraffe', 'Blue Whale', 'Tiger'], e: '🐋' },
    { q: 'Which animal can change color?', a: 'Chameleon', choices: ['Frog', 'Lizard', 'Chameleon', 'Snake'], e: '🦎' },
    { q: 'What is a baby cat called?', a: 'Kitten', choices: ['Puppy', 'Cub', 'Kitten', 'Chick'], e: '🐱' },
  ],
  colors: [
    { q: 'What color is the sky?', a: 'Blue', choices: ['Red', 'Green', 'Blue', 'Yellow'], e: '☀️' },
    { q: 'What color is grass?', a: 'Green', choices: ['Blue', 'Green', 'Yellow', 'Brown'], e: '🌿' },
    { q: 'What color is an apple?', a: 'Red', choices: ['Red', 'Blue', 'Purple', 'Orange'], e: '🍎' },
    { q: 'What color is the sun?', a: 'Yellow', choices: ['Red', 'Orange', 'Yellow', 'White'], e: '☀️' },
    { q: 'What color is a pumpkin?', a: 'Orange', choices: ['Red', 'Yellow', 'Orange', 'Purple'], e: '🎃' },
    { q: 'What color is a grape?', a: 'Purple', choices: ['Red', 'Blue', 'Purple', 'Green'], e: '🍇' },
    { q: 'What color is snow?', a: 'White', choices: ['Gray', 'Blue', 'White', 'Silver'], e: '❄️' },
    { q: 'What color is a banana?', a: 'Yellow', choices: ['Green', 'Orange', 'Yellow', 'White'], e: '🍌' },
    { q: 'What color is the ocean?', a: 'Blue', choices: ['Green', 'Blue', 'Teal', 'Gray'], e: '🌊' },
    { q: 'What color is chocolate?', a: 'Brown', choices: ['Black', 'Brown', 'Red', 'Orange'], e: '🍫' },
  ],
  shapes: [
    { q: 'How many sides does a triangle have?', a: '3', choices: ['2', '3', '4', '5'], e: '🔺' },
    { q: 'What shape is a pizza?', a: 'Circle', choices: ['Square', 'Circle', 'Triangle', 'Oval'], e: '🍕' },
    { q: 'What shape is a book?', a: 'Rectangle', choices: ['Square', 'Circle', 'Rectangle', 'Diamond'], e: '📚' },
    { q: 'How many corners does a square have?', a: '4', choices: ['3', '4', '5', '6'], e: '🟥' },
    { q: 'What shape is a wheel?', a: 'Circle', choices: ['Oval', 'Circle', 'Square', 'Rectangle'], e: '⚙️' },
    { q: 'What shape has 5 points?', a: 'Star', choices: ['Circle', 'Star', 'Diamond', 'Heart'], e: '⭐' },
    { q: 'What shape is an egg?', a: 'Oval', choices: ['Circle', 'Round', 'Oval', 'Sphere'], e: '🥚' },
    { q: 'What shape is a stop sign?', a: 'Octagon', choices: ['Circle', 'Square', 'Octagon', 'Hexagon'], e: '🛑' },
  ],
  fruits: [
    { q: 'Which fruit is yellow and curved?', a: 'Banana', choices: ['Lemon', 'Banana', 'Mango', 'Pear'], e: '🍌' },
    { q: 'Which fruit is red and round?', a: 'Apple', choices: ['Tomato', 'Apple', 'Cherry', 'Strawberry'], e: '🍎' },
    { q: 'Which fruit is orange colored?', a: 'Orange', choices: ['Mango', 'Lemon', 'Orange', 'Papaya'], e: '🍊' },
    { q: 'Which fruit has seeds inside?', a: 'Watermelon', choices: ['Banana', 'Mango', 'Watermelon', 'Grape'], e: '🍉' },
    { q: 'Which is a tropical fruit?', a: 'Pineapple', choices: ['Apple', 'Pear', 'Pineapple', 'Cherry'], e: '🍍' },
    { q: 'Which fruit is very sour?', a: 'Lemon', choices: ['Mango', 'Grape', 'Lemon', 'Strawberry'], e: '🍋' },
    { q: 'Which fruit comes in bunches?', a: 'Grapes', choices: ['Cherry', 'Grapes', 'Plum', 'Blueberry'], e: '🍇' },
    { q: 'Which fruit is red with seeds outside?', a: 'Strawberry', choices: ['Cherry', 'Raspberry', 'Strawberry', 'Tomato'], e: '🍓' },
  ],
}

export const SHOP_AVS = [
  { id: 'av_def', emoji: '😊', label: 'Default', price: 0 },
  { id: 'av_cat', emoji: '🐱', label: 'Cat', price: 20 },
  { id: 'av_star', emoji: '⭐', label: 'Star', price: 30 },
  { id: 'av_ninja', emoji: '🥷', label: 'Ninja', price: 50 },
  { id: 'av_wizard', emoji: '🧙', label: 'Wizard', price: 75 },
  { id: 'av_robot', emoji: '🤖', label: 'Robot', price: 100 },
  { id: 'av_dino', emoji: '🦕', label: 'Dino', price: 80 },
  { id: 'av_unicorn', emoji: '🦄', label: 'Unicorn', price: 120 },
  { id: 'av_dragon', emoji: '🐲', label: 'Dragon', price: 150 },
]

export const SHOP_THS = [
  { id: 'th_def', label: 'Classic Purple', color: '#5E5CE6', price: 0 },
  { id: 'th_ocean', label: 'Ocean Blue', color: '#0A84FF', price: 40 },
  { id: 'th_forest', label: 'Forest Green', color: '#30D158', price: 40 },
  { id: 'th_sunset', label: 'Sunset Orange', color: '#FF9F0A', price: 60 },
  { id: 'th_rose', label: 'Rose Pink', color: '#FF375F', price: 60 },
  { id: 'th_galaxy', label: 'Galaxy Dark', color: '#BF5AF2', price: 100 },
]

export const TEMPLATES = [
  {
    id: 'animals',
    title: 'Animals',
    icon: '🐾',
    color: '#30D158',
    items: [
      { w: 'Dog', e: '🐶', hint: 'Says woof' },
      { w: 'Cat', e: '🐱', hint: 'Says meow' },
      { w: 'Elephant', e: '🐘', hint: 'Has a trunk' },
      { w: 'Lion', e: '🦁', hint: 'King of jungle' },
      { w: 'Tiger', e: '🐯', hint: 'Has stripes' },
    ],
  },
  {
    id: 'fruits',
    title: 'Fruits',
    icon: '🍎',
    color: '#FF453A',
    items: [
      { w: 'Apple', e: '🍎', hint: 'Red and sweet' },
      { w: 'Banana', e: '🍌', hint: 'Yellow fruit' },
      { w: 'Orange', e: '🍊', hint: 'Citrus fruit' },
      { w: 'Mango', e: '🥭', hint: 'Tropical and sweet' },
      { w: 'Grape', e: '🍇', hint: 'Grows in bunch' },
    ],
  },
  {
    id: 'numbers',
    title: 'Numbers',
    icon: '🔢',
    color: '#5E5CE6',
    items: [
      { w: 'One', e: '1️⃣', hint: '1 apple' },
      { w: 'Two', e: '2️⃣', hint: '2 balloons' },
      { w: 'Three', e: '3️⃣', hint: '3 stars' },
      { w: 'Four', e: '4️⃣', hint: '4 wheels' },
      { w: 'Five', e: '5️⃣', hint: '5 fingers' },
    ],
  },
]
